### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Kreuger** [vinsce/gneelight#4]
Hey I am unable to install the app with flatpak. It gives me the following error:

`flatpak install --user gneelight.flatpak
error: The application me.vinsce.Gneelight/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found
`

**Comment by vinsce** [comment]
Hi @Kreuger, it seems the Gnome platform version tagged with "master" is no more available.
I updated the Gneelight flatpak build to target a specific platform version and it should fix the issue.

You can try the [1.0.4 release](https://github.com/vinsce/gneelight/blob/v1.0.4/flatpak/gneelight.flatpak)

**Comment by Kreuger** [comment]
Hey thanks for the reply but it gave me a similar error. 
`flatpak install gneelight.flatpak
error: The application me.vinsce.Gneelight/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.38 which was not found`

Would you be able to provide a deb package?

**Comment by vinsce** [comment]
Hi @Kreuger , which distro and version are you using?

The runtime `org.gnome.Platform/x86_64/3.38` should be available in the [flathub repository](https://flatpak.org/), you can add the flathub remote as described [here](https://flatpak.org/setup/):
```flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo```

Once you have added the remote you can try to reinstall Gneelight.

I you still have the problem, can you check if and which version of the Gnome runtime do you have installed?
You can use `flatpak list --user` to list all the installed packages and search for "GNOME Application Platform".

You can also try to manually install the required runtime with:
`flatpak install --user runtime/org.gnome.Platform/x86_64/3.38`

**Comment by Kreuger** [comment]
Im using Lubuntu 20.04. I dont think I've used flatpak apps before so I guess I didnt have anything required. But it still wont work.

https://imgbox.com/cGtvzMV0

**Comment by vinsce** [comment]
Try with
```flatpak install --user gneelight.flatpak```
instead of
```flatpak install gneelight.flatpak```

As I can see from your screenshot, the runtime is installed with the `--user` flag, but for the application you are trying to install it system wide (without `--user`)

**Comment by Kreuger** [comment]
It says it installed. How do I launch it? I don't see it in my menu.

**Comment by vinsce** [comment]
If it doesn't appear in the applications menu you can launch it from terminal:
```flatpak run --user me.vinsce.Gneelight```

**Comment by Kreuger** [comment]
Thanks, that worked. I will create a desktop shortcut manually. However it isnt able to detect either of my lights. I have a Colour 1S bulb and the led light strip.

**Comment by vinsce** [comment]
I am glad you solved :) 
In order to use Gneelight, you should first enable "development mode" on your bulb through the YeeLight app.
If you still encounter connectivity problems you can open a specific issue, currently I have only tested it with a white bulb.

**Comment by andrii482** [comment]
> Hi @Kreuger , which distro and version are you using?
> 
> The runtime `org.gnome.Platform/x86_64/3.38` should be available in the [flathub repository](https://flatpak.org/), you can add the flathub remote as described [here](https://flatpak.org/setup/):
> `flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
> 
> Once you have added the remote you can try to reinstall Gneelight.
> 
> I you still have the problem, can you check if and which version of the Gnome runtime do you have installed?
> You can use `flatpak list --user` to list all the installed packages and search for "GNOME Application Platform".
> 
> You can also try to manually install the required runtime with:
> `flatpak install --user runtime/org.gnome.Platform/x86_64/3.38`

definitely, you need to update your **_readme.md_** with  this steps  :)

**Comment by andrii482** [comment]
hm... anyway, In my case this not working anyway :( 

```~$ flatpak install --user runtime/org.gnome.Platform/x86_64/3.38
Looking for matches…
Found similar ref(s) for ‘runtime/org.gnome.Platform/x86_64/3.38’ in remote ‘flathub’ (user).
Use this remote? [Y/n]: 


        ID                                                       Branch             Op            Remote             Download
 1. [✓] org.freedesktop.Platform.GL.default                      20.08              i             flathub             95,3 MB / 95,9 MB
 2. [✓] org.freedesktop.Platform.GL.nvidia-455-45-01             1.4                i             flathub            133,5 MB / 133,6 MB
 3. [✓] org.freedesktop.Platform.VAAPI.Intel                     20.08              i             flathub             11,1 MB / 11,2 MB
 4. [✓] org.freedesktop.Platform.openh264                        2.0                i             flathub              1,5 MB / 1,5 MB
 5. [✓] org.gnome.Platform.Locale                                3.38               i             flathub             16,8 kB / 326,0 MB
 6. [✓] org.gtk.Gtk3theme.Breeze-Dark                            3.22               i             flathub             92,4 kB / 156,9 kB
 7. [✓] org.gnome.Platform                                       3.38               i             flathub            292,0 MB / 343,3 MB

Installation complete.
DATE: 01/11/21
TIME:15:39:39

~$ sudo flatpak install --user gneelight.flatpak
error: The application me.vinsce.Gneelight/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found
DATE: 01/11/21
TIME:15:44:56

~$ sudo flatpak install  gneelight.flatpak
error: The application me.vinsce.Gneelight/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found
DATE: 01/11/21
TIME:15:45:31
```
<details> 
  <summary> some spoiler of  <b>"~$ flatpak list"</b>  </summary>
    <pre>
~$ flatpak list 
Name                                                         Application ID                                          Version                Branch            Origin             Installation
Headset                                                      co.headsetapp.headset                                   3.2.1                  stable            flathub            system
Gydl                                                         com.github.JannikHv.Gydl                                0.1.1                  stable            flathub            system
VGrive                                                       com.github.bcedu.vgrive                                 1.6.0                  stable            flathub            system
MoonPlayer                                                   com.github.coslyk.MoonPlayer                            3.6                    stable            flathub            system
CherryTree                                                   com.giuspen.cherrytree                                  0.99.29                stable            flathub            system
Peek                                                         com.uploadedlobster.peek                                1.5.1                  stable            flathub            system
FreeTube                                                     io.freetubeapp.FreeTube                                 0.10.0 Beta            stable            flathub            system
HexChat                                                      io.github.Hexchat                                       2.14.3                 stable            flathub            system
ONVIFViewer                                                  net.meijn.onvifviewer                                   0.12                   stable            flathub            system
Freedesktop.org Application Platform version 1.6             org.freedesktop.Platform                                1.6                    1.6               flathub            system
Freedesktop Platform                                         org.freedesktop.Platform                                18.08.39               18.08             flathub            system
Freedesktop Platform                                         org.freedesktop.Platform                                19.08.12               19.08             flathub            system
Freedesktop Platform                                         org.freedesktop.Platform                                20.08.3                20.08             flathub            system
i386                                                         org.freedesktop.Platform.Compat.i386                                           20.08             flathub            system
default                                                      org.freedesktop.Platform.GL.default                                            19.08             flathub            system
default                                                      org.freedesktop.Platform.GL.default                                            20.08             flathub            system
default                                                      org.freedesktop.Platform.GL.default                                            20.08             flathub            user
nvidia-455-45-01                                             org.freedesktop.Platform.GL.nvidia-455-45-01                                   1.4               flathub            system
nvidia-455-45-01                                             org.freedesktop.Platform.GL.nvidia-455-45-01                                   1.4               flathub            user
default                                                      org.freedesktop.Platform.GL32.default                                          20.08             flathub            system
Adwaita icon theme                                           org.freedesktop.Platform.Icontheme.Adwaita                                     1.0               flathub            system
Intel VAAPI Driver                                           org.freedesktop.Platform.VAAPI.Intel                                           1.6               flathub            system
Intel                                                        org.freedesktop.Platform.VAAPI.Intel                                           18.08             flathub            system
Intel                                                        org.freedesktop.Platform.VAAPI.Intel                                           19.08             flathub            system
Intel                                                        org.freedesktop.Platform.VAAPI.Intel                                           20.08             flathub            system
Intel                                                        org.freedesktop.Platform.VAAPI.Intel                                           20.08             flathub            user
FFmpeg extension                                             org.freedesktop.Platform.ffmpeg                                                1.6               flathub            system
ffmpeg-full                                                  org.freedesktop.Platform.ffmpeg-full                                           20.08             flathub            system
html5-codecs                                                 org.freedesktop.Platform.html5-codecs                                          18.08             flathub            system
openh264                                                     org.freedesktop.Platform.openh264                                              19.08             flathub            system
openh264                                                     org.freedesktop.Platform.openh264                       2.1.0                  2.0               flathub            system
openh264                                                     org.freedesktop.Platform.openh264                       2.1.0                  2.0               flathub            user
Freedesktop SDK                                              org.freedesktop.Sdk                                     18.08.39               18.08             flathub            system
Freedesktop SDK                                              org.freedesktop.Sdk                                     19.08.12               19.08             flathub            system
Geeqie                                                       org.geeqie.Geeqie                                       v1.5.1                 stable            flathub            system
GNOME Application Platform version 3.24                      org.gnome.Platform                                                             3.24              flathub            system
GNOME Application Platform version 3.26                      org.gnome.Platform                                                             3.26              flathub            system
GNOME Application Platform version 3.28                      org.gnome.Platform                                                             3.28              flathub            system
GNOME Application Platform version 3.30                      org.gnome.Platform                                                             3.30              flathub            system
GNOME Application Platform version 3.32                      org.gnome.Platform                                                             3.32              flathub            system
GNOME Application Platform version 3.34                      org.gnome.Platform                                                             3.34              flathub            system
GNOME Application Platform version 3.36                      org.gnome.Platform                                                             3.36              flathub            system
GNOME Application Platform version 3.38                      org.gnome.Platform                                                             3.38              flathub            system
GNOME Application Platform version 3.38                      org.gnome.Platform                                                             3.38              flathub            user
GNOME Software Development Kit version 3.34                  org.gnome.Sdk                                                                  3.34              flathub            system
GNOME Software Development Kit version 3.38                  org.gnome.Sdk                                                                  3.38              flathub            system
Locale                                                       org.gnome.Tomboy.Locale                                                        stable            flathub            system
Adwaita dark GTK theme                                       org.gtk.Gtk3theme.Adwaita-dark                                                 3.22              flathub            system
Arc-Dark Gtk theme                                           org.gtk.Gtk3theme.Arc-Dark                                                     3.22              flathub            system
Breeze Gtk theme                                             org.gtk.Gtk3theme.Breeze-Dark                                                  3.22              flathub            system
Breeze Gtk theme                                             org.gtk.Gtk3theme.Breeze-Dark                                                  3.22              flathub            user
Greybird-Geeko GTK+ Theme                                    org.gtk.Gtk3theme.Greybird-Geeko-Dark                                          3.22              flathub            system
Qogir-ubuntu-dark GTK theme                                  org.gtk.Gtk3theme.Qogir-ubuntu-dark                                            3.34              flathub            system
Deepin Gtk+ theme (dark)                                     org.gtk.Gtk3theme.deepin-dark                                                  3.22              flathub            system
Adwaita theme                                                org.kde.KStyle.Adwaita                                                         5.13              flathub            system
Adwaita theme                                                org.kde.KStyle.Adwaita                                                         5.14              flathub            system
Adwaita theme                                                org.kde.KStyle.Adwaita                                                         5.15              flathub            system
KDE Application Platform                                     org.kde.Platform                                                               5.13              flathub            system
KDE Application Platform                                     org.kde.Platform                                                               5.14              flathub            system
KDE Application Platform                                     org.kde.Platform                                                               5.15              flathub            system
QGnomePlatform                                               org.kde.PlatformTheme.QGnomePlatform                                           5.13              flathub            system
Discover                                                     org.kde.discover                                        5.20.3                 master            kdeapps            system
Phoenicis PlayOnLinux                                        org.phoenicis.playonlinux                               5.0-alpha-3            stable            flathub            system
DATE: 01/11/21
TIME:15:49:44
~$
  </pre>
 </details>

**Comment by Kreuger** [comment]
I dont think you should be using sudo for it when youre using the --user switch.
