### ISSUE TITLE
Unable to detect my lights

### ISSUE THREAD

**Issue by Kreuger** [vinsce/gneelight#6]
Now that I have the app running (thanks). I am unable to detect my lights. I know you have said that you have only tested it with the white bulb. I do have LAN control set up already because I can control them using Home Assistant. I have no idea what else to try for getting them detected.

**Comment by Kreuger** [comment]
After restarting my laptop due to installing updates, I can now see my Colour 1S bulb (It shows as the Color 4 with the correct IP address) however the app just shows the loading icon indefinitely. When running it from the terminal, there is no output. 

Edit: Im able to toggle the light off and on from the tray icon so that's a good start.

**Comment by vinsce** [comment]
Hi @Kreuger , I've create a [new branch](https://github.com/vinsce/gneelight/tree/hotfix/forever_loading) to address this issue and I've published a [new flatpak package](https://github.com/vinsce/gneelight/blob/hotfix/forever_loading/flatpak/gneelight.flatpak) with bulb discovery logs. Can you try this new version and show me the logs you see in the terminal?

Also, can you attach a screenshot of the main Gneelight window? Are you able to see the discovered bulbs in the upper side?

**Comment by Kreuger** [comment]
Hey I just downloaded the new package and when I went to install it, the branch shows as the master. It is now unable to detect my bulb again. I don't know if it's worth noting that I have since updated from 20.04 to 20.10. On a side note, I am now able to see the app in my menu. https://imgbox.com/Hv5QnByx

Edit: It's no longer attempting to refresh constantly in the UI.

**Comment by vinsce** [comment]
Hi, if you have connectivity problems it can also be due to a firewall or other types of blocks (e.g. router side, like in [this discussion](https://gitlab.com/stavros/python-yeelight/-/issues/29)).

I've also updated the underlying yeelight library used to communicate with lights (new package [here](https://github.com/vinsce/gneelight/blob/hotfix/forever_loading/flatpak/gneelight.flatpak))

**Comment by Kreuger** [comment]
After installing the new package and disabling my VPN, I can see my one bulb again but not the LED strip. However, there's still nothing showing in the main screen and it seems stuck on the loading again. But I am still able to toggle the light off and on when right clicking the tray icon. Speaking of which, are you able to add a checkmark or something to indicate that it's on so that when I go to right click it, it's shown beside the toggle button? Or change it to only show off/on depending on the state?

Here is the output from the terminal: 

```
`flatpak run --user me.vinsce.Gneelight
Discovery start requested
Show loading True (control_only = False). Current loading status: False
Start bulb discovery

(Gneelight:3): Gdk-CRITICAL **: 15:06:29.571: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Discovered [<BulbWrapper.BulbWrapper object at 0x7f2c90f75250>] bulbs
IP		192.168.0.218
Port		55443
Model		color4
Firmware version		31
Power		off
Brightness		50
Color Mode		color_mode (1)
Color Temperature		4000
RGB		16721920
HUE		9
Saturation		100
Capabilities		['get_prop', 'set_default', 'set_power', 'toggle', 'set_bright', 'set_scene', 'cron_add', 'cron_get', 'cron_del', 'start_cf', 'stop_cf', 'set_ct_abx', 'adjust_ct', 'set_name', 'set_adjust', 'adjust_bright', 'adjust_color', 'set_rgb', 'set_hsv', 'set_music', 'udp_new', 'udp_keep_alive', 'chroma']
Show loading False (control_only = False). Current loading status: True
Selected bulb 192.168.0.218 (color4)
Found requested bulb
Showing new selected bulb
Show loading True (control_only = True). Current loading status: False
Updating bulb status async
Updating bulb status sync
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/src/BulbWrapper.py", line 103, in update_status_sync
`


```

**Comment by Kreuger** [comment]
I opened the app today and suddenly my light strip is now detected and I can trigger it from the tray icon. However, I still have the issue with it constantly loading.

https://imgbox.com/pR76ms08

Edit: I closed the app and fired it up from the terminal and now neither one of them are visible.

Edit 2: I was able to get them to show again by restarting my laptop so now I have some terminal output for you. Hopefully this will help to figure out why it hangs on the loading screen.

```
robbie@lenovo-b570:~$ flatpak run --user me.vinsce.Gneelight
Discovery start requested
Show loading True (control_only = False). Current loading status: False
Start bulb discovery

(Gneelight:3): Gdk-CRITICAL **: 15:00:02.658: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Discovered [<BulbWrapper.BulbWrapper object at 0x7fab14998250>, <BulbWrapper.BulbWrapper object at 0x7fab149983a0>] bulbs
IP		192.168.0.218
Port		55443
Model		color4
Firmware version		31
Power		off
Brightness		50
Color Mode		color_mode (1)
Color Temperature		4000
RGB		16721920
HUE		9
Saturation		100
Capabilities		['get_prop', 'set_default', 'set_power', 'toggle', 'set_bright', 'set_scene', 'cron_add', 'cron_get', 'cron_del', 'start_cf', 'stop_cf', 'set_ct_abx', 'adjust_ct', 'set_name', 'set_adjust', 'adjust_bright', 'adjust_color', 'set_rgb', 'set_hsv', 'set_music', 'udp_new', 'udp_keep_alive', 'chroma']
IP		192.168.0.219
Port		55443
Model		strip6
Firmware version		13
Power		off
Brightness		50
Color Mode		color_mode (1)
Color Temperature		4000
RGB		16711680
Saturation		100
Capabilities		['get_prop', 'set_default', 'set_power', 'toggle', 'set_bright', 'set_scene', 'cron_add', 'cron_get', 'cron_del', 'start_cf', 'stop_cf', 'set_name', 'set_adjust', 'adjust_bright', 'set_ct_abx', 'adjust_ct', 'adjust_color', 'set_rgb', 'set_hsv', 'set_music', 'udp_new', 'udp_keep_alive', 'chroma']
Show loading False (control_only = False). Current loading status: True
Selected bulb 192.168.0.218 (color4)
Found requested bulb
Showing new selected bulb
Show loading True (control_only = True). Current loading status: False
Updating bulb status async
Updating bulb status sync
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/src/BulbWrapper.py", line 103, in update_status_sync
    self.bulb_status = BulbStatus(self.get_bulb().get_properties())
  File "/app/lib/python3.8/site-packages/yeelight/main.py", line 463, in get_properties
    response = self.send_command("get_prop", requested_properties)
  File "/app/lib/python3.8/site-packages/yeelight/main.py", line 545, in send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: Bulb closed the connection.
Selected bulb 192.168.0.218 (color4)
Found requested bulb
Show loading True (control_only = True). Current loading status: True
Updating bulb status async
Updating bulb status sync
Selected bulb 192.168.0.219 (strip6)
Found requested bulb
Showing new selected bulb
Show loading True (control_only = True). Current loading status: True
Updating bulb status async
Updating bulb status sync
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/src/BulbWrapper.py", line 103, in update_status_sync
    self.bulb_status = BulbStatus(self.get_bulb().get_properties())
  File "/app/lib/python3.8/site-packages/yeelight/main.py", line 463, in get_properties
    response = self.send_command("get_prop", requested_properties)
  File "/app/lib/python3.8/site-packages/yeelight/main.py", line 545, in send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: Bulb closed the connection.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/src/BulbWrapper.py", line 103, in update_status_sync
    self.bulb_status = BulbStatus(self.get_bulb().get_properties())
  File "/app/lib/python3.8/site-packages/yeelight/main.py", line 463, in get_properties
    response = self.send_command("get_prop", requested_properties)
  File "/app/lib/python3.8/site-packages/yeelight/main.py", line 545, in send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: Bulb closed the connection.`
```

**Comment by Kreuger** [comment]
The app is very inconsistent with being able to detect my lights. Sometimes it shows one (the Colour 1S bulb) and sometimes it shows both. But only the Colour 1S bulb is available to control. My light strip shows up but when I click to change, I just get the reloading icon again. Running from the terminal shows nothing.
